services:
  postgres:
    image: postgres:16
    container_name: gym-postgres
    environment:
      POSTGRES_DB: gym_platform
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gym
    ports:
      - "5432:5432"
    volumes:
      - gym_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: gym-redis
    ports:
      - "6379:6379"

volumes:
  gym_postgres_data:
